spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kitaecoding999@gmail.com
    password: aaa0332601
    thymeleaf:
      cache: false
      prefix: classpath:/templates
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true